name: robotinn_customer_app
description: "RobotInn Customer App - On-demand Food & Grocery Delivery Mobile Application built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  google_sign_in: ^6.2.2

  
  provider: ^6.1.2


  shared_preferences: ^2.3.5
  intl: ^0.20.3
  http: ^1.2.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  geocoding: 5.0.0

  
  google_maps_flutter: ^2.10.0


  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  path_provider_android: 2.2.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/3d_brands/
    - assets/images/3d_categories/
